"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import RoadmapCard from "@/components/RoadmapCard";
import type { RoadmapData } from "@/lib/api";

export default function RoadmapPage() {
  const [roadmap, setRoadmap] = useState<RoadmapData | null>(null);
  const [ready, setReady] = useState(false);

  useEffect(() => {
    const raw = localStorage.getItem("wayfarer_roadmap");
    if (raw) {
      try {
        setRoadmap(JSON.parse(raw));
      } catch {
        // corrupted — treat as empty
      }
    }
    setReady(true);
  }, []);

  if (!ready) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="w-6 h-6 border-4 border-brand-600 border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  if (!roadmap) {
    return (
      <div className="max-w-lg mx-auto px-6 py-12">
        <div className="w-14 h-14 rounded-2xl bg-brand-50 flex items-center justify-center mb-6">
          <svg className="w-7 h-7 text-brand-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7" />
          </svg>
        </div>
        <h1 className="text-2xl font-display font-semibold text-gray-900 mb-2">My Roadmap</h1>
        <p className="text-sm text-gray-600 leading-relaxed mb-6">
          This is where your personalised visa path will live once Compass has generated it from your
          chat. You haven&apos;t created a roadmap yet.
        </p>
        <div className="rounded-2xl border border-gray-100 bg-white p-5 mb-8 text-left">
          <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-3">
            What you&apos;ll see here
          </p>
          <ul className="text-sm text-gray-600 space-y-2.5 list-disc list-inside marker:text-brand-500">
            <li>
              <span className="-ml-1">Your tasks and your employer&apos;s tasks, in order</span>
            </li>
            <li>
              <span className="-ml-1">Priority and status (available, in progress, blocked)</span>
            </li>
            <li>
              <span className="-ml-1">Shortcuts to open Compass on any step when you need help</span>
            </li>
          </ul>
        </div>
        <Link
          href="/dashboard/chat"
          className="inline-flex items-center gap-2 px-5 py-2.5 bg-brand-600 hover:bg-brand-700 text-white text-sm font-medium rounded-xl transition-colors"
        >
          Go to Chat to build your roadmap →
        </Link>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto px-8 py-10">
      <h1 className="text-2xl font-display font-semibold text-gray-900 mb-1">My Roadmap</h1>
      <p className="text-xs text-gray-400 mb-8">Generated by Compass based on your conversation.</p>
      <RoadmapCard data={roadmap} />
    </div>
  );
}
